
package com.asan.cms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.asan.transaction.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CMS_Transaction_Ejb", targetNamespace = "http://transaction.asan.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMSTransactionEjb {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerCard", targetNamespace = "http://transaction.asan.com/", className = "com.asan.transaction.RegisterCard")
    @ResponseWrapper(localName = "registerCardResponse", targetNamespace = "http://transaction.asan.com/", className = "com.asan.transaction.RegisterCardResponse")
    @Action(input = "http://transaction.asan.com/CMS_Transaction_Ejb/registerCardRequest", output = "http://transaction.asan.com/CMS_Transaction_Ejb/registerCardResponse")
    public String registerCard(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCardInfo", targetNamespace = "http://transaction.asan.com/", className = "com.asan.transaction.GetCardInfo")
    @ResponseWrapper(localName = "getCardInfoResponse", targetNamespace = "http://transaction.asan.com/", className = "com.asan.transaction.GetCardInfoResponse")
    @Action(input = "http://transaction.asan.com/CMS_Transaction_Ejb/getCardInfoRequest", output = "http://transaction.asan.com/CMS_Transaction_Ejb/getCardInfoResponse")
    public String getCardInfo(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doCardTransactionReverse", targetNamespace = "http://transaction.asan.com/", className = "com.asan.transaction.DoCardTransactionReverse")
    @ResponseWrapper(localName = "doCardTransactionReverseResponse", targetNamespace = "http://transaction.asan.com/", className = "com.asan.transaction.DoCardTransactionReverseResponse")
    @Action(input = "http://transaction.asan.com/CMS_Transaction_Ejb/doCardTransactionReverseRequest", output = "http://transaction.asan.com/CMS_Transaction_Ejb/doCardTransactionReverseResponse")
    public String doCardTransactionReverse(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doCardTransaction", targetNamespace = "http://transaction.asan.com/", className = "com.asan.transaction.DoCardTransaction")
    @ResponseWrapper(localName = "doCardTransactionResponse", targetNamespace = "http://transaction.asan.com/", className = "com.asan.transaction.DoCardTransactionResponse")
    @Action(input = "http://transaction.asan.com/CMS_Transaction_Ejb/doCardTransactionRequest", output = "http://transaction.asan.com/CMS_Transaction_Ejb/doCardTransactionResponse")
    public String doCardTransaction(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TransactionInquiry")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "TransactionInquiry", targetNamespace = "http://transaction.asan.com/", className = "com.asan.transaction.TransactionInquiry")
    @ResponseWrapper(localName = "TransactionInquiryResponse", targetNamespace = "http://transaction.asan.com/", className = "com.asan.transaction.TransactionInquiryResponse")
    @Action(input = "http://transaction.asan.com/CMS_Transaction_Ejb/TransactionInquiryRequest", output = "http://transaction.asan.com/CMS_Transaction_Ejb/TransactionInquiryResponse")
    public String transactionInquiry(
        @WebParam(name = "request", targetNamespace = "")
        String request);

}
